version: '3'
services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    image: dashboard
    env_file:
      - ./.envfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
    restart: always