const states = [
    { text: 'AL', value: 'Alabama' },
    { text: 'AK', value: 'Alaska' },
    { text: 'AZ', value: 'Arizona' },
    { text: 'CA', value: 'California' },
    { text: 'CO', value: 'Colorado' },
    { text: 'CT', value: 'Connecticut' },
    { text: 'DE', value: 'Delaware' },
    { text: 'DC', value: 'Washington, D.C.' },
    { text: 'FL', value: 'Florida' },
    { text: 'GA', value: 'Georgia' },
    { text: 'HI', value: 'Hawaii' },
    { text: 'ID', value: 'Idaho' },
    { text: 'IL', value: 'Illinois' },
    { text: 'IN', value: 'Indiana' },
    { text: 'IA', value: 'Iowa' },
    { text: 'KS', value: 'Kansas' },
    { text: 'KY', value: 'Kentucky' },
    { text: 'LA', value: 'Louisiana' },
    { text: 'ME', value: 'Maine' },
    { text: 'MD', value: 'Maryland' },
    { text: 'MA', value: 'Massachusetts' },
    { text: 'MI', value: 'Michigan' },
    { text: 'MN', value: 'Minnesota' },
    { text: 'MS', value: 'Mississippi' },
    { text: 'MO', value: 'Missouri' },
    { text: 'MT', value: 'Montana' },
    { text: 'NE', value: 'Nebraska' },
    { text: 'NV', value: 'Nevada' },
    { text: 'NH', value: 'New Hampshire' },
    { text: 'NJ', value: 'New Jersey' },
    { text: 'NM', value: 'New Mexico' },
    { text: 'NY', value: 'New York' },
    { text: 'NC', value: 'North Carolina' },
    { text: 'ND', value: 'North Dakota' },
    { text: 'OH', value: 'Ohio' },
    { text: 'OK', value: 'Oklahoma' },
    { text: 'OR', value: 'Oregon' },
    { text: 'PA', value: 'Pennsylvania' },
    { text: 'RI', value: 'Rhode Island' },
    { text: 'SC', value: 'South Carolina' },
    { text: 'SD', value: 'South Dakota' },
    { text: 'TN', value: 'Tennessee' },
    { text: 'TX', value: 'Texas' },
    { text: 'UT', value: 'Utah' },
    { text: 'VT', value: 'Vermont' },
    { text: 'VA', value: 'Virginia' },
    { text: 'WA', value: 'Washington' },
    { text: 'WV', value: 'West Virginia' },
    { text: 'WI', value: 'Wisconsin' },
    { text: 'WY', value: 'Wyoming' }
];

export default states;
